import { useEffect, useState } from 'react'
import { ArrowLeft, Loader2, Play, Square, Video } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  ASPECT_RATIOS,
  estimateSpokenSeconds,
  PACING_OPTIONS,
  type HeyGenVoice,
  type OptionsFormState,
  type StoryboardScene,
  VIDEO_CTAS,
  VIDEO_TONES,
  VIDEO_TOPICS,
} from '@/lib/marketing-video'

type ScriptReviewStepProps = {
  script: string
  onScriptChange: (script: string) => void
  videoAgentPrompt: string
  onVideoAgentPromptChange: (prompt: string) => void
  scenes: StoryboardScene[]
  options: OptionsFormState
  voices: HeyGenVoice[]
  voiceId: string | null
  onVoiceChange: (voiceId: string) => void
  isRegenerating: boolean
  isGeneratingVideo: boolean
  onRegenerate: () => void
  onRegenerateWithChanges: (instruction: string) => void
  onBack: () => void
  onGenerateVideo: () => void
  scriptError: string | null
  videoError: string | null
  consentRequired?: boolean
  profileVoiceId?: string | null
}

export function ScriptReviewStep({
  script,
  onScriptChange,
  videoAgentPrompt,
  onVideoAgentPromptChange,
  scenes,
  options,
  voices,
  voiceId,
  onVoiceChange,
  isRegenerating,
  isGeneratingVideo,
  onRegenerate,
  onRegenerateWithChanges,
  onBack,
  onGenerateVideo,
  scriptError,
  videoError,
  consentRequired = false,
  profileVoiceId,
}: ScriptReviewStepProps) {
  const [refineInput, setRefineInput] = useState('')
  const [showRefine, setShowRefine] = useState(false)
  
  const [playingVoiceId, setPlayingVoiceId] = useState<string | null>(null)
  const [audioInstance, setAudioInstance] = useState<HTMLAudioElement | null>(null)

  const seconds = estimateSpokenSeconds(script)
  const wordCount = script.trim().split(/\s+/).filter(Boolean).length

  const topicLabel = VIDEO_TOPICS.find((t) => t.id === options.topic)?.label
  const toneLabel = VIDEO_TONES.find((t) => t.id === options.tone)?.label
  const pacingLabel = PACING_OPTIONS.find((p) => p.id === options.pacing)?.label
  const ratioLabel = ASPECT_RATIOS.find((r) => r.id === options.aspectRatio)?.label
  const ctaLabel = VIDEO_CTAS.find((c) => c.id === options.cta)?.label

  // Cleanup audio on unmount or audio instance change
  useEffect(() => {
    return () => {
      if (audioInstance) {
        audioInstance.pause()
      }
    }
  }, [audioInstance])

  const togglePlayVoice = (voice: HeyGenVoice) => {
    if (playingVoiceId === voice.voice_id) {
      if (audioInstance) {
        audioInstance.pause()
        audioInstance.currentTime = 0
      }
      setPlayingVoiceId(null)
      setAudioInstance(null)
      return
    }

    if (audioInstance) {
      audioInstance.pause()
    }

    const previewUrl = voice.preview_audio_url
    if (!previewUrl) return

    const audio = new Audio(previewUrl)
    setAudioInstance(audio)
    setPlayingVoiceId(voice.voice_id)
    audio.play().catch(() => {
      setPlayingVoiceId(null)
      setAudioInstance(null)
    })
    audio.onended = () => {
      setPlayingVoiceId(null)
      setAudioInstance(null)
    }
  }

  const selectedVoice = voices.find((v) => v.voice_id === voiceId)

  return (
    <div className="grid gap-8 xl:grid-cols-[1fr_300px]">
      <div className="space-y-6">
        <div>
          <h2 className="text-lg font-semibold text-white">Your Video Storyboard</h2>
          <p className="mt-1 text-sm text-[var(--color-text-secondary)]">
            Review the script, scenes, and visual prompts generated by GROQ.
          </p>
        </div>

        {/* Spoken Script Section */}
        <div className="space-y-2">
          <Label className="text-white font-medium">Spoken Script</Label>
          <div className="rounded-sm border border-[#2a2a2a] bg-[#1a1a1a] p-4">
            <textarea
              value={script}
              onChange={(event) => onScriptChange(event.target.value)}
              rows={8}
              className="w-full resize-y bg-transparent text-sm leading-relaxed text-white focus:outline-none"
            />
          </div>
          <p className="text-xs text-[var(--color-text-secondary)]">
            ~{seconds} seconds when spoken ({wordCount} words)
          </p>
        </div>

        <div className="flex flex-wrap gap-3">
          <Button
            type="button"
            variant="outline"
            disabled={isRegenerating}
            onClick={onRegenerate}
            className="border-[#CFB87C] bg-transparent text-[#CFB87C] hover:bg-[#CFB87C]/10"
          >
            {isRegenerating ? (
              <>
                <Loader2 className="mr-2 size-4 animate-spin" />
                Regenerating Video Plan...
              </>
            ) : (
              'Regenerate'
            )}
          </Button>
          <Button
            type="button"
            variant="ghost"
            onClick={() => setShowRefine((v) => !v)}
            className="text-[var(--color-text-secondary)] hover:text-white"
          >
            Refine with instruction →
          </Button>
        </div>

        {showRefine ? (
          <div className="flex flex-col gap-2 sm:flex-row">
            <input
              type="text"
              value={refineInput}
              onChange={(event) => setRefineInput(event.target.value)}
              placeholder='e.g. "make it shorter" or "change scene 2 to a kitchen"'
              className="flex-1 rounded-sm border border-[#333] bg-[#111] px-3 py-2 text-sm text-white focus:outline focus:outline-2 focus:outline-[#CFB87C]"
            />
            <Button
              type="button"
              disabled={!refineInput.trim() || isRegenerating}
              onClick={() => {
                onRegenerateWithChanges(refineInput.trim())
                setRefineInput('')
              }}
              className="bg-[#CFB87C] text-[#0a0a0a] hover:bg-[#dcc487]"
            >
              Apply
            </Button>
          </div>
        ) : null}

        {/* Dynamic Storyboard Scenes */}
        {scenes && scenes.length > 0 && (
          <div className="space-y-4 pt-6 border-t border-[#2a2a2a]">
            <div>
              <h3 className="text-base font-semibold text-white">Scene-by-Scene Breakdown</h3>
              <p className="text-xs text-[var(--color-text-secondary)]">
                HeyGen Video Agent will compose these environments and layouts sequentially.
              </p>
            </div>
            <div className="grid gap-4 sm:grid-cols-2">
              {scenes.map((scene) => (
                <div key={scene.scene_number} className="rounded-sm border border-[#2a2a2a] bg-[#111] p-4 space-y-2">
                  <div className="flex items-center gap-2">
                    <span className="flex size-5 items-center justify-center rounded-full bg-[#CFB87C]/20 text-[10px] font-bold text-[#CFB87C]">
                      {scene.scene_number}
                    </span>
                    <span className="text-xs font-semibold text-white uppercase tracking-wider">
                      Scene {scene.scene_number}
                    </span>
                  </div>
                  <div className="space-y-1">
                    <p className="text-[10px] text-[#CFB87C] font-semibold uppercase tracking-wider">Visual Environment:</p>
                    <p className="text-xs text-[var(--color-text-secondary)] leading-relaxed italic">
                      "{scene.visual}"
                    </p>
                  </div>
                  <div className="space-y-1">
                    <p className="text-[10px] text-[#CFB87C] font-semibold uppercase tracking-wider">Spoken Script:</p>
                    <p className="text-xs text-white leading-relaxed">
                      {scene.script}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Video Agent Prompt */}
        <div className="space-y-2 pt-6 border-t border-[#2a2a2a]">
          <div className="flex items-center justify-between">
            <Label htmlFor="agent-prompt" className="text-white font-medium">
              HeyGen Video Agent Prompt
            </Label>
            <p className="text-[10px] text-[var(--color-text-secondary)]">
              Double check and customize prompt before rendering.
            </p>
          </div>
          <textarea
            id="agent-prompt"
            value={videoAgentPrompt}
            onChange={(e) => onVideoAgentPromptChange(e.target.value)}
            rows={5}
            className="w-full rounded-sm border border-[#333] bg-[#111] px-3.5 py-2.5 text-xs text-gray-300 focus:outline focus:outline-2 focus:outline-[#CFB87C]"
          />
        </div>

        <Button
          type="button"
          variant="ghost"
          onClick={onBack}
          className="text-[var(--color-text-secondary)] hover:text-white"
        >
          <ArrowLeft className="mr-2 size-4" />
          Change settings
        </Button>

        {scriptError ? (
          <p className="text-sm text-red-300" role="alert">
            {scriptError}
          </p>
        ) : null}
      </div>

      <aside className="space-y-4 rounded-sm border border-[#2a2a2a] bg-[#1a1a1a] p-5 xl:sticky xl:top-8 xl:self-start">
        <h3 className="text-sm font-semibold text-white">Video settings</h3>
        <dl className="space-y-2 text-xs text-[var(--color-text-secondary)]">
          <div>
            <dt className="text-[#CFB87C]">Topic</dt>
            <dd className="text-white">{topicLabel}</dd>
          </div>
          <div>
            <dt className="text-[#CFB87C]">Tone</dt>
            <dd className="text-white">{toneLabel}</dd>
          </div>
          <div>
            <dt className="text-[#CFB87C]">Pacing</dt>
            <dd className="text-white">{pacingLabel}</dd>
          </div>
          <div>
            <dt className="text-[#CFB87C]">Aspect ratio</dt>
            <dd className="text-white">{ratioLabel}</dd>
          </div>
          <div>
            <dt className="text-[#CFB87C]">End with</dt>
            <dd className="text-white">{ctaLabel}</dd>
          </div>
        </dl>

        <div className="space-y-2 border-t border-[#2a2a2a] pt-4">
          <Label className="text-[var(--color-text-secondary)]">HeyGen voice</Label>
          <div className="flex gap-2">
            <div className="flex-1">
              <Select value={voiceId ?? undefined} onValueChange={onVoiceChange}>
                <SelectTrigger className="border-[#333] bg-[#111] text-white">
                  <SelectValue placeholder="Select a voice" />
                </SelectTrigger>
                <SelectContent>
                  {profileVoiceId && (
                    <SelectItem value={profileVoiceId} className="font-semibold text-[#CFB87C]">
                      🗣️ My Cloned Voice (Default)
                    </SelectItem>
                  )}
                  {voices.map((voice) => (
                    <SelectItem key={voice.voice_id} value={voice.voice_id}>
                      {voice.name}
                      {voice.gender ? ` · ${voice.gender}` : ''}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            {selectedVoice?.preview_audio_url && (
              <Button
                type="button"
                variant="outline"
                size="icon"
                onClick={() => togglePlayVoice(selectedVoice)}
                className="border-[#333] text-white hover:bg-[#111] shrink-0"
                title="Preview voice"
              >
                {playingVoiceId === selectedVoice.voice_id ? (
                  <Square className="size-3 text-[#CFB87C] fill-[#CFB87C]" />
                ) : (
                  <Play className="size-3 text-[#CFB87C]" />
                )}
              </Button>
            )}
          </div>
        </div>

        <Button
          type="button"
          disabled={!script.trim() || !voiceId || isGeneratingVideo || consentRequired}
          onClick={onGenerateVideo}
          className="mt-2 h-11 w-full bg-[#CFB87C] font-semibold text-[#0a0a0a] hover:bg-[#dcc487] disabled:opacity-50"
        >
          {isGeneratingVideo ? (
            <>
              <Loader2 className="mr-2 size-4 animate-spin" />
              Starting video...
            </>
          ) : consentRequired ? (
            'Complete consent first'
          ) : (
            <>
              <Video className="mr-2 size-4" />
              Generate My Video
            </>
          )}
        </Button>

        {consentRequired ? (
          <p className="text-xs text-amber-200/90 mt-2">
            Complete identity verification in Step 1 (Avatar) before generating your video.
          </p>
        ) : null}

        {videoError ? (
          <p className="text-sm text-red-300 mt-2" role="alert">
            {videoError}
          </p>
        ) : null}
      </aside>
    </div>
  )
}
