export type FieldType =
  | 'text'
  | 'number'
  | 'currency'
  | 'textarea'
  | 'select'
  | 'radio'
  | 'multiselect'
  | 'date'
  | 'room_row'
  | 'yes_no'

export interface NtreisField {
  key: string
  label: string
  type: FieldType
  required: boolean
  options?: string[]
  roomFeatures?: string[]
  maxLength?: number
  placeholder?: string
  helpText?: string
  conditionalOn?: { key: string; value: string | string[] }
}

export interface NtreisSection {
  id: number
  name: string
  pdfPages: number[]
  fields: NtreisField[]
}

export interface RoomRowValue {
  room_name?: string
  level?: string
  length?: number | string
  width?: number | string
  features?: string[]
}

export type FormData = Record<string, unknown>

export type SectionStatus = 'complete' | 'partial' | 'empty'


export const ROOM_FEATURES: Record<string, string[]> = {
  bedroom_primary: [
    'Cedar Closet(s)',
    'Custom Closet System',
    'Dual Master Baths',
    'Dual Sinks',
    'Ensuite Bath',
    'Fireplace',
    'Garden Tub',
    'Hollywood Bath',
    'Jetted Tub',
    'Linen Closet',
    'Medicine Cabinet',
    'Separate Shower',
    'Separate Vanities',
    'Shower Body Sprays',
    'Sitting Area in Master',
    'Steam Shower',
    'Walk-in Closet(s)',
  ],
  bedroom_2nd_primary: [
    'Cedar Closet(s)',
    'Custom Closet System',
    'Dual Master Baths',
    'Dual Sinks',
    'Ensuite Bath',
    'Fireplace',
    'Garden Tub',
    'Hollywood Bath',
    'Jetted Tub',
    'Linen Closet',
    'Medicine Cabinet',
    'Separate Shower',
    'Separate Vanities',
    'Shower Body Sprays',
    'Sitting Area in Master',
    'Steam Shower',
    'Walk-in Closet(s)',
    'Built-in Cabinets',
    'Built-In Desk',
  ],
  bedroom_3: [
    'Built-in Cabinets',
    'Built-in Desk',
    'Cedar Closet(s)',
    'Ceiling Fan(s)',
    'Custom Closet System',
    'Ensuite Bath',
    'Fireplace',
    'Split Bedrooms',
    'Walk-in Closet(s)',
  ],
  bedroom_4: [
    'Built-in Cabinets',
    'Built-in Desk',
    'Cedar Closet(s)',
    'Ceiling Fan(s)',
    'Custom Closet System',
    'Ensuite Bath',
    'Fireplace',
    'Split Bedrooms',
    'Walk-in Closet(s)',
  ],
  bedroom_5: [
    'Built-in Cabinets',
    'Built-in Desk',
    'Cedar Closet(s)',
    'Ceiling Fan(s)',
    'Custom Closet System',
    'Ensuite Bath',
    'Fireplace',
    'Split Bedrooms',
    'Walk-in Closet(s)',
  ],
  bedroom_6: [
    'Built-in Cabinets',
    'Built-in Desk',
    'Cedar Closet(s)',
    'Ceiling Fan(s)',
    'Custom Closet System',
    'Ensuite Bath',
    'Fireplace',
    'Split Bedrooms',
    'Walk-in Closet(s)',
  ],
  bath_primary: [
    'Bidet',
    'Built-in Cabinets',
    'Built-in Desk',
    'Cedar Closet(s)',
    'Concrete Countertop',
    'Corian/Corian Type',
    'Custom Closet System',
    'Double Shower',
    'Drip/Dry Area',
    'Dual Master Baths',
    'Dual Sinks',
    'Dumbwaiter',
    'Ensuite Bath',
    'Floor Drain',
    'Garden Tub',
    'Granite/Granite Type',
    'Hollywood Bath',
    'Jack & Jill Bath',
    'Jetted Tub',
    'Linen Closet',
    'Medicine Cabinet',
    'Natural Stone/Granite Type',
    'Second Sink',
    'Separate Shower',
    'Separate Vanities',
    'Shower Body Sprays',
    'Sitting Area in Master',
    'Solid Surface/Non-Natural Type',
    'Steam Shower',
    'Tile Counters',
  ],
  bath_full: [
    'Bidet',
    'Built-in Cabinets',
    'Concrete Countertop',
    'Corian/Corian Type',
    'Double Shower',
    'Drip/Dry Area',
    'Dual Master Baths',
    'Dual Sinks',
    'Ensuite Bath',
    'Fireplace',
    'Garden Tub',
    'Granite/Granite Type',
    'Hollywood Bath',
    'Jack & Jill Bath',
    'Jetted Tub',
    'Linen Closet',
    'Medicine Cabinet',
    'Natural Stone/Granite Type',
    'Separate Shower',
    'Separate Vanities',
    'Shower Body Sprays',
    'Solid Surface/Non-Natural Type',
    'Steam Shower',
    'Tile Counters',
  ],
  bath_half: [
    'Bidet',
    'Corian/Corian Type',
    'Granite/Granite Type',
    'Medicine Cabinet',
  ],
  kitchen: [
    'Breakfast Bar',
    'Built-in Cabinets',
    'Butlers Pantry',
    'Ceiling Fan(s)',
    'Concrete Countertop',
    'Corian/Corian Type',
    'Dual Sinks',
    'Dumbwaiter',
    'Eat-in Kitchen',
    'Farm Sink',
    'Galley Kitchen',
    'Granite/Granite Type',
    'Kitchen Island',
    'Natural Stone/Granite Type',
    'Pantry',
    'Pot Filler',
    'Recycle Bin',
    'Room for Freezer',
    'Second Pantry',
    'Second Sink',
    'Solid Surface/Non-Natural Type',
    'Tile Counters',
    'Utility in Kitchen',
    'Walk-in Pantry',
    'Water Line to Refrigerator',
  ],
  utility_room: [
    'Built-in Cabinets',
    'Drip/Dry Area',
    'Dual Sinks',
    'Dumbwaiter',
    'Floor Drain',
    'Linen Closet',
    'Other',
    'Pot Filler',
    'Recycle Bin',
    'Room for Freezer',
    'Second Pantry',
    'Second Sink',
    'Separate Utility Room',
    'Sink in Utility',
    'Utility Closet',
    'Utility in Garage',
  ],
}

export const NTREIS_SECTIONS: NtreisSection[] = [

  // ─── SECTION 1 — Property Information (PDF page 1) ───────────────────
  {
    id: 1, name: "Property Information", pdfPages: [1],
    fields: [
      { key: "listing_type", label: "Listing Type", 
        type: "select", required: true,
        options: ["listing", "buyer", "lease"] },
      { key: "seller_name", label: "Seller Name", 
        type: "text", required: true },
      { key: "seller_email", label: "Seller Email", 
        type: "text", required: true },
      { key: "seller_phone", label: "Seller Phone", 
        type: "text", required: true },
      { key: "property_sub_type", label: "Property Sub Type", 
        type: "select", required: true,
        options: ["Single Family Residence","Condominium","Townhouse",
          "Mobile Home","Manufactured Home","Farm"] },
      { key: "property_attached_yn", label: "Property Attached", 
        type: "yes_no", required: true },
      { key: "listing_agreement_type", label: "Listing Agreement Type", 
        type: "select", required: true,
        options: ["Exclusive Right to Sell","Exclusive Right With Exception",
          "Exclusive Agency","Exclusive Agency with Reservation",
          "Exclusive Agency to Lease"] },
      { key: "transaction_type", label: "Transaction Type", 
        type: "select", required: true,
        options: ["For Sale","For Sale/Lease"] },
      { key: "for_lease_mls_number", label: "For Lease MLS #", 
        type: "text", required: false,
        conditionalOn: { key: "transaction_type", value: "For Sale/Lease" } },
      { key: "adult_community_yn", label: "Adult Community", 
        type: "yes_no", required: false },
      { key: "will_subdivide_yn", label: "Will Subdivide", 
        type: "select", required: true,
        options: ["Yes","No","Subdivided"] },
      { key: "accessory_unit_yn", label: "Accessory Unit", 
        type: "yes_no", required: false },
      { key: "accessory_unit_sqft", label: "Accessory Unit SqFt", 
        type: "number", required: false,
        conditionalOn: { key: "accessory_unit_yn", value: "Yes" } },
      { key: "accessory_unit_type", label: "Accessory Unit Type", 
        type: "select", required: false,
        options: ["Accessory Dwelling Unit (AdU)","Guest Quarters",
          "Other","Pool House"],
        conditionalOn: { key: "accessory_unit_yn", value: "Yes" } },
      { key: "architectural_style", label: "Architectural Style", 
        type: "multiselect", required: false,
        options: ["A-Frame","Barndominium","Colonial","Contemporary/Modern",
          "Craftsman","Early American","English","French","Geo/Dome","Loft",
          "Mediterranean","Mid-Century Modern","Modern Farmhouse","Oriental",
          "Prairie","Ranch","Southwestern","Spanish","Split Level","Studio",
          "Traditional","Tudor","Victorian","Other"] },
      { key: "year_built_status", label: "Year Built / Construction Status", 
        type: "select", required: true,
        options: ["Preowned","New Construction - Complete",
          "New Construction - Incomplete","Proposed","Unknown"] },
      { key: "list_price", label: "List Price", 
        type: "currency", required: true },
      { key: "list_date", label: "List Date", 
        type: "date", required: true },
      { key: "expire_date", label: "Expire Date", 
        type: "date", required: true },
      { key: "year_built", label: "Year Built", 
        type: "number", required: true },
      { key: "year_built_source", label: "Year Built Source", 
        type: "select", required: false,
        options: ["Appraiser","Assessor","Builder","Estimated","Owner",
          "Public Records","See Remarks","Other"] },
      { key: "living_area_sqft", label: "SqFt / Living Area", 
        type: "number", required: true },
      { key: "sqft_source", label: "SqFt Source", 
        type: "select", required: false,
        options: ["Appraiser","Assessor","Builder","Other","Owner",
          "Plans","Public Records","See Remarks"] },
      { key: "parcel_id", label: "Parcel ID", 
        type: "text", required: true },
      { key: "additional_parcel_id", label: "Additional Parcel ID", 
        type: "text", required: false },
      { key: "multi_parcel_id_yn", label: "Multi Parcel ID", 
        type: "yes_no", required: true },
      { key: "housing_type", label: "Housing Type", 
        type: "select", required: true,
        options: ["Apartment","Attached or 1/2 Duplex","Condo/Townhome",
          "Designated Historical Home","Farm/Ranch House",
          "Garden/Zero Lot Line","Hi Rise","Historical/Conservation Dist.",
          "Interval Ownership","Lake House","Log Cabin",
          "Manufactured (certificate exch)","Mobile Doublewide w/Land",
          "Mobile Singlewide w/Land","Resort Property","Single Detached",
          "Underground","Vacation Home"] },
      { key: "construction_material", label: "Construction Material", 
        type: "multiselect", required: false,
        options: ["Aluminum Siding","Block","Board & Batten Siding","Brick",
          "Cedar","Concrete","Fiber Cement","Fiberglass Siding","Frame",
          "Log","Metal Siding","Plaster","Radiant Barrier","Rock/Stone",
          "Siding","Steel Siding","Stone Veneer","Stucco","Tilt Wall",
          "Unknown","Vinyl Siding","Wood","See Remarks","Other"] },
    ]
  },

  // ─── SECTION 2 — Location & School Information (PDF page 2) ──────────
  {
    id: 2, name: "Location & Schools", pdfPages: [2],
    fields: [
      // Address fields already captured in Step 0 — show as read-only 
      // summary here with an "Edit address" link back to Step 0
      { key: "_address_summary", label: "Property Address", 
        type: "text", required: false,
        helpText: "Captured in address step above — edit there if needed" },
      { key: "lot", label: "Lot", type: "text", required: false },
      { key: "tax_block", label: "Tax Block", type: "text", required: false },
      { key: "planned_development", label: "Planned Development", 
        type: "text", required: false },
      { key: "additional_legal_desc", label: "Additional Legal Description", 
        type: "textarea", required: false, maxLength: 500 },
      { key: "lake_name", label: "Lake Name", type: "text", required: false },
      { key: "school_district", label: "School District", 
        type: "text", required: true },
      { key: "elementary_school", label: "Elementary School Name", 
        type: "text", required: false },
      { key: "junior_high_school", label: "Junior High School Name", 
        type: "text", required: false },
      { key: "senior_high_school", label: "Senior High School Name", 
        type: "text", required: false },
      { key: "primary_school", label: "Primary School Name", 
        type: "text", required: false },
      { key: "middle_school", label: "Middle School Name", 
        type: "text", required: false },
      { key: "high_school", label: "High School Name", 
        type: "text", required: false },
      { key: "intermediate_school", label: "Intermediate School Name", 
        type: "text", required: false },
    ]
  },

  // ─── SECTION 3 — Room Details: Bedrooms (PDF pages 3–4) ──────────────
  {
    id: 3, name: "Room Details — Bedrooms", pdfPages: [3,4],
    fields: [
      { key: "bedrooms_total", label: "# Bedrooms", 
        type: "number", required: true },
      { key: "bathrooms_full", label: "# Full Baths", 
        type: "number", required: true },
      { key: "bathrooms_half", label: "# Half Baths", 
        type: "number", required: true },
      { key: "levels", label: "Levels", 
        type: "text", required: true },
      { key: "living_areas", label: "# Living Areas", 
        type: "number", required: true },
      { key: "dining_areas", label: "# Dining Areas", 
        type: "number", required: true },
      // Primary bedroom room row
      { key: "bedroom_primary", label: "Bedroom — Primary", 
        type: "room_row", required: false,
        roomFeatures: ROOM_FEATURES['bedroom_primary'] },
      // room_row renders: Level | Length | Width | Features multiselect
      // Primary bedroom features:
      // Cedar Closet(s), Custom Closet System, Dual Master Baths, 
      // Dual Sinks, Ensuite Bath, Fireplace, Garden Tub, Hollywood Bath,
      // Jetted Tub, Linen Closet, Medicine Cabinet, Separate Shower,
      // Separate Vanities, Shower Body Sprays, Sitting Area in Master,
      // Steam Shower, Walk-in Closet(s)
      // Store as: { level, length, width, features: string[] }
      { key: "bedroom_2nd_primary", label: "Bedroom — 2nd Primary", 
        type: "room_row", required: false,
        roomFeatures: ROOM_FEATURES['bedroom_2nd_primary'] },
      // 2nd primary features same as primary PLUS: Built-in Cabinets, 
      // Built-In Desk
      // Additional bedrooms (up to 6)
      {
        key: "bedroom_3",
        label: "Bedroom 3",
        type: "room_row",
        required: false,
        roomFeatures: ROOM_FEATURES['bedroom_3'],
      },
      {
        key: "bedroom_4",
        label: "Bedroom 4",
        type: "room_row",
        required: false,
        roomFeatures: ROOM_FEATURES['bedroom_4'],
      },
      {
        key: "bedroom_5",
        label: "Bedroom 5",
        type: "room_row",
        required: false,
        roomFeatures: ROOM_FEATURES['bedroom_5'],
      },
      {
        key: "bedroom_6",
        label: "Bedroom 6",
        type: "room_row",
        required: false,
        roomFeatures: ROOM_FEATURES['bedroom_6'],
      },
      // Additional bedroom features: Built-in Cabinets, Built-in Desk, 
      // Cedar Closet(s), Ceiling Fan(s), Custom Closet System, 
      // Ensuite Bath, Fireplace, Split Bedrooms, Walk-in Closet(s)
    ]
  },

  // ─── SECTION 4 — Room Details: Bathrooms (PDF pages 5–6) ─────────────
  {
    id: 4, name: "Room Details — Bathrooms", pdfPages: [5,6],
    fields: [
      { key: "bath_primary", label: "Bath — Primary", 
        type: "room_row", required: false,
        roomFeatures: ROOM_FEATURES['bath_primary'] },
      // Primary bath features: Bidet, Built-in Cabinets, Built-in Desk,
      // Cedar Closet(s), Concrete Countertop, Corian/Corian Type,
      // Custom Closet System, Double Shower, Drip/Dry Area,
      // Dual Master Baths, Dual Sinks, Dumbwaiter, Ensuite Bath,
      // Floor Drain, Garden Tub, Granite/Granite Type, Hollywood Bath,
      // Jack & Jill Bath, Jetted Tub, Linen Closet, Medicine Cabinet,
      // Natural Stone/Granite Type, Second Sink, Separate Shower,
      // Separate Vanities, Shower Body Sprays, Sitting Area in Master,
      // Solid Surface/Non-Natural Type, Steam Shower, Tile Counters
      { key: "bath_full", label: "Bath — Full", 
        type: "room_row", required: false,
        roomFeatures: ROOM_FEATURES['bath_full'] },
      // Full bath features: Bidet, Built-in Cabinets, Concrete Countertop,
      // Corian/Corian Type, Double Shower, Drip/Dry Area, Dual Master Baths,
      // Dual Sinks, Ensuite Bath, Fireplace, Garden Tub, Granite/Granite Type,
      // Hollywood Bath, Jack & Jill Bath, Jetted Tub, Linen Closet,
      // Medicine Cabinet, Natural Stone/Granite Type, Separate Shower,
      // Separate Vanities, Shower Body Sprays, Solid Surface/Non-Natural Type,
      // Steam Shower, Tile Counters
      { key: "bath_half", label: "Bath — Half", 
        type: "room_row", required: false,
        roomFeatures: ROOM_FEATURES['bath_half'] },
      // Half bath features: Bidet, Corian/Corian Type, 
      // Granite/Granite Type, Medicine Cabinet
    ]
  },

  // ─── SECTION 5 — Room Details: Kitchen & Utility (PDF page 6) ────────
  {
    id: 5, name: "Room Details — Kitchen & Utility", pdfPages: [6],
    fields: [
      {
        key: "kitchen",
        label: "Kitchen",
        type: "room_row",
        required: false,
        roomFeatures: ROOM_FEATURES['kitchen'],
      },
      // Kitchen features: Breakfast Bar, Built-in Cabinets, Butlers Pantry,
      // Ceiling Fan(s), Concrete Countertop, Corian/Corian Type,
      // Dual Sinks, Dumbwaiter, Eat-in Kitchen, Farm Sink, Galley Kitchen,
      // Granite/Granite Type, Kitchen Island, Natural Stone/Granite Type,
      // Pantry, Pot Filler, Recycle Bin, Room for Freezer, Second Pantry,
      // Second Sink, Solid Surface/Non-Natural Type, Tile Counters,
      // Utility in Kitchen, Walk-in Pantry, Water Line to Refrigerator
      { key: "utility_room", label: "Utility Room", 
        type: "room_row", required: false,
        roomFeatures: ROOM_FEATURES['utility_room'] },
      // Utility features: Built-in Cabinets, Drip/Dry Area, Dual Sinks,
      // Dumbwaiter, Floor Drain, Linen Closet, Other, Pot Filler,
      // Recycle Bin, Room for Freezer, Second Pantry, Second Sink,
      // Separate Utility Room, Sink in Utility, Utility Closet,
      // Utility in Garage
    ]
  },

  // ─── SECTION 6 — Room Details: Additional Rooms (PDF page 7) ─────────
  {
    id: 6, name: "Room Details — Additional Rooms", pdfPages: [7],
    fields: [
      // Up to 10 additional rooms, each: room name + level + length + width
      // No features for additional rooms — just dimensions
      { key: "additional_room_1", label: "Additional Room 1", 
        type: "room_row", required: false },
      { key: "additional_room_2", label: "Additional Room 2", 
        type: "room_row", required: false },
      { key: "additional_room_3", label: "Additional Room 3", 
        type: "room_row", required: false },
      { key: "additional_room_4", label: "Additional Room 4", 
        type: "room_row", required: false },
      { key: "additional_room_5", label: "Additional Room 5", 
        type: "room_row", required: false },
      { key: "additional_room_6", label: "Additional Room 6", 
        type: "room_row", required: false },
      { key: "additional_room_7", label: "Additional Room 7", 
        type: "room_row", required: false },
      { key: "additional_room_8", label: "Additional Room 8", 
        type: "room_row", required: false },
      { key: "additional_room_9", label: "Additional Room 9", 
        type: "room_row", required: false },
      { key: "additional_room_10", label: "Additional Room 10", 
        type: "room_row", required: false },
    ]
  },

  // ─── SECTION 7 — Features: Interior & Security (PDF page 8) ──────────
  {
    id: 7, name: "Interior & Security Features", pdfPages: [8],
    fields: [
      { key: "accessibility_yn", label: "Accessibility Features", 
        type: "yes_no", required: true },
      { key: "accessibility_features", label: "Accessibility Features", 
        type: "multiselect", required: false,
        options: ["Approach with Ramp","Accessible Bath - Full",
          "Accessible Bath - Half+Hall","Accessible Bedroom",
          "Accessible Doors","Elec. & Env. Controls",
          "Accessible Elevator Installed","Accessible Entrance",
          "Hearing-Impairment","Accessible Grip","Accessible Hallway(s)",
          "Accessible Kitchen","Customized Wheelchair Access",
          "Meets ADA Requirements","Smart Technology","Stair Lift"],
        conditionalOn: { key: "accessibility_yn", value: "Yes" } },
      { key: "interior_features", label: "Interior Features", 
        type: "multiselect", required: true,
        options: ["Built-in Features","Built-in Wine Cooler",
          "Cable TV Available","Cathedral Ceiling(s)","Cedar Closet(s)",
          "Central Vacuum","Chandelier","Decorative Lighting",
          "Double Vanity","Dry Bar","Dumbwaiter","Eat-in Kitchen",
          "Elevator","Flat Screen Wiring","Granite Counters",
          "High Speed Internet Available","In-Law Suite Floorplan",
          "Kitchen Island","Loft","Multiple Staircases","Natural Woodwork",
          "Open Floorplan","Other","Paneling","Pantry","Smart Home System",
          "Sound System Wiring","Tile Counters","Vaulted Ceiling(s)",
          "Wainscoting","Walk-In Closet(s)","Wet Bar","Wired for Data",
          "Second Primary Bedroom"] },
      { key: "security_features", label: "Security Features", 
        type: "multiselect", required: false,
        options: ["Burglar","Carbon Monoxide Detector(s)","Fire Alarm",
          "Fire Sprinkler System","Firewall(s)","Gated Community",
          "Key Card Entry","Prewired","Security Gate","Security Guard",
          "Security Lights","Security Service","Security System",
          "Security System Leased","Security System Owned",
          "Smoke Detector(s)","Unknown","Wireless","Other"] },
      { key: "laundry_features", label: "Laundry Features", 
        type: "multiselect", required: false,
        options: ["Dryer - Electric Hookup","Dryer - Gas Hookup",
          "In Garage","In Hall","In Kitchen","In Utility Room",
          "Laundry Chute","W/D - Full Size W/D Area",
          "W/D - Stacked W/D Area","Washer Hookup","Other",
          "On Site","None"] },
      { key: "smart_home_yn", label: "Smart Home Features", 
        type: "yes_no", required: true },
    ]
  },

  // ─── SECTION 8 — Features: Pool, Foundation, Roof, Flooring (PDF p 8) 
  {
    id: 8, name: "Pool, Foundation & Exterior", pdfPages: [8],
    fields: [
      { key: "pool_yn", label: "Pool on Property", 
        type: "yes_no", required: true },
      { key: "pool_features", label: "Pool Features", 
        type: "multiselect", required: false,
        options: ["Above Ground","Cabana","Diving Board","Fenced",
          "Fiberglass","Gunite","Heated","In Ground","Indoor","Infinity",
          "Lap","Outdoor Pool","Pool Cover","Pool Sweep","Pool/Spa Combo",
          "Private","Pump","Salt Water","Sep. Spa/Hot Tub","Solar Cover",
          "Solar Heat","Sport","Vinyl","Water Feature","Waterfall","Other"],
        conditionalOn: { key: "pool_yn", value: "Yes" } },
      { key: "basement_yn", label: "Basement", 
        type: "yes_no", required: true },
      { key: "foundation", label: "Foundation", 
        type: "multiselect", required: false,
        options: ["Block","Bois DArc Post","Brick/Mortar","Combination",
          "Concrete Perimeter","Pillar/Post/Pier","Slab","Stone",
          "Other","None"] },
      { key: "roof", label: "Roof", 
        type: "multiselect", required: false,
        options: ["Asphalt","Built-up","Composition","Concrete",
          "Fiber Cement","Fiberglass","Flat","Metal","Mixed","Shake",
          "Shingle","Slate","Spanish Tile","Synthetic","Tar/Gravel",
          "Tile","Wood","Other"] },
      { key: "flooring", label: "Flooring", 
        type: "multiselect", required: false,
        options: ["Adobe","Bamboo","Brick","Brick/Adobe","Carpet",
          "Ceramic Tile","Clay","Combination","Concrete","Cork","Dirt",
          "Granite","Hardwood","Laminate","Linoleum","Luxury Vinyl Plank",
          "Marble","Painted/Stained","Parquet","Pavers","Reclaimed Wood",
          "Simulated Wood","Slate","Softwood","Stamped","Stone",
          "Sustainable","Terrazzo","Tile","Travertine Stone","Varies",
          "Vinyl","Wood","Wood Under Carpet","None","Other","See Remarks"] },
      { key: "community_features", label: "Community Features", 
        type: "multiselect", required: false,
        options: ["Airport/Runway","Boat Ramp","Campground","Club House",
          "Common Elevator","Community Dock","Community Pool",
          "Community Sprinkler","Curbs","Electric Car Charging Station",
          "Fishing","Fitness Center","Gated","Golf","Greenbelt",
          "Guarded Entrance","Hangar","Horse Facilities",
          "Jogging Path/Bike Path","Lake","Laundry","Marina","Park",
          "Perimeter Fencing","Playground","Pool","Racquet Ball",
          "Restaurant","RV Parking","Sauna","Sidewalks","Spa",
          "Stable(s)","Tennis Court(s)","Other"] },
    ]
  },

  // ─── SECTION 9 — Features: Fireplaces (PDF page 8) ───────────────────
  {
    id: 9, name: "Fireplaces", pdfPages: [8],
    fields: [
      { key: "fireplace_count", label: "# Fireplaces", 
        type: "number", required: true },
      { key: "fireplace_features", label: "Fireplace Features", 
        type: "multiselect", required: false,
        options: ["Bath","Bedroom","Blower Fan","Brick","Circulating",
          "Decorative","Den","Dining Room","Double Sided","Electric",
          "EPA Certified Wood Stove","EPA Qualified Fireplace",
          "Family Room","Fire Pit","Freestanding","Gas","Gas Logs",
          "Gas Starter","Glass Doors","Great Room","Heatilator","Insert",
          "Kitchen","Library","Living Room","Masonry","Master Bedroom",
          "Metal","Outside","Pellet Stove","Propane","Raised Hearth",
          "Recreation Room","Sealed Combustion","See Remarks",
          "See Through Fireplace","Stone","Ventless","Wood Burning",
          "Wood Burning Stove","Zero Clearance","Other","None"] },
    ]
  },

  // ─── SECTION 10 — Features: Appliances & Equipment (PDF page 9) ──────
  {
    id: 10, name: "Appliances & Equipment", pdfPages: [9],
    fields: [
      { key: "appliances", label: "Appliances", 
        type: "multiselect", required: true,
        options: ["Built-in Coffee Maker","Built-in Gas Range",
          "Built-in Refrigerator","Commercial Grade Range",
          "Commercial Grade Vent","Dishwasher","Disposal","Dryer",
          "Electric Cooktop","Electric Oven","Electric Range",
          "Electric Water Heater","Gas Cooktop","Gas Oven","Gas Range",
          "Gas Water Heater","Ice Maker","Indoor Grill","Microwave",
          "Oven-Convection","Oven-Double","Plumbed For Gas in Kitchen",
          "Refrigerator","Tankless Water Heater","Trash Compactor",
          "Vented Exhaust Fan","Warming Drawer","Washer","Water Filter",
          "Water Purifier","Other","Water Softener","None"] },
      { key: "other_equipment", label: "Other Equipment", 
        type: "multiselect", required: false,
        options: ["Air Purifier","Call Listing Agent","Compressor",
          "DC Well Pump","Dehumidifier","Farm Equipment","Fuel Tank(s)",
          "Generator","Home Theater","Intercom","Irrigation Equipment",
          "List Available","Livestock Equipment","Negotiable",
          "Orchard Equipment","Rotary Antenna","Satellite Dish",
          "TV Antenna","Varies By Unit","Other","None"] },
      { key: "window_features", label: "Window Features", 
        type: "multiselect", required: false,
        options: ["Bay Window(s)","Electric Shades","Plantation Shutters",
          "Skylight(s)","Window Coverings"] },
      { key: "patio_porch_features", label: "Patio & Porch Features", 
        type: "multiselect", required: false,
        options: ["Awning(s)","Covered","Deck","Enclosed","Front Porch",
          "Glass Enclosed","Patio","Rear Porch","Roof Top Deck/Patio",
          "Screened","Side Porch","Terrace","Wrap Around",
          "See Remarks","Other","None"] },
      { key: "special_notes", label: "Special Notes", 
        type: "multiselect", required: false,
        options: ["Aerial Photo","Affordable Housing","Age-Restricted",
          "Agent Related to Owner","Build to Suit","Deed Restrictions",
          "Deep Hole Test","Environ. Study Complete",
          "Feasibility Study Available","Flood Plain","Flowage Easement",
          "Highline","Historical","HUD","Inland/Wetland Restrictions",
          "Meets ADA Guidelines","Owner/Agent","Perc Test",
          "Phase I Complete","Phase II Complete","Pipeline",
          "Res. Service Contract","Right of First Refusal",
          "Section 8 Qualified","Special Assessments",
          "Special Contracts/Provisions","Survey Available",
          "Utility Easement","Verify Flood Insurance",
          "Verify Rollback Tax","Verify Tax Exemptions","Other"] },
    ]
  },

  // ─── SECTION 11 — Parking & Garage (PDF page 9) ──────────────────────
  {
    id: 11, name: "Parking & Garage", pdfPages: [9],
    fields: [
      { key: "carport_spaces", label: "# Carport Spaces", 
        type: "number", required: true },
      { key: "garage_spaces", label: "# Garage Spaces", 
        type: "number", required: false },
      { key: "covered_spaces_total", label: "# Covered Spaces (Total)", 
        type: "number", required: true },
      { key: "garage_yn", label: "Garage", 
        type: "yes_no", required: true },
      { key: "attached_garage_yn", label: "Attached Garage", 
        type: "yes_no", required: false },
      { key: "garage_length", label: "Garage Length (ft)", 
        type: "number", required: false },
      { key: "garage_width", label: "Garage Width (ft)", 
        type: "number", required: false },
      { key: "garage_height", label: "Garage Height (ft)", 
        type: "number", required: false },
      { key: "parking_features", label: "Parking Features", 
        type: "multiselect", required: true,
        options: ["Additional Parking","Aggregate","Alley Access",
          "Asphalt","Assigned","Attached Carport","Basement","Boat",
          "Carport","Circular Driveway","Common","Community Structure",
          "Concrete","Converted Garage","Covered","Deck","Deeded",
          "Detached Carport","Direct Access","Drive Through","Driveway",
          "Electric Gate","Elec Vehicle Charging Station(s)","Enclosed",
          "Epoxy Flooring","Garage","Garage Door Opener","Garage Double Door",
          "Garage Faces Front","Garage Faces Rear","Garage Faces Side",
          "Garage Single Door","Gated","Golf Cart Garage","Gravel","Guest",
          "Heated Garage","Inside Entrance","Kitchen Level","Leased",
          "Lighted","No Garage","None","Off Site","Off Street","On Site",
          "On Street","Open","Other","Outside","Oversized","Parking Lot",
          "Parking Pad","Paved","Paver Block","Permit Required","Private",
          "RV Access/Parking","RV Carport","RV Garage","RV Gated",
          "Secured","See Remarks","Shared Driveway","Side By Side",
          "Storage","Tandem","Unassigned","Underground","Unpaved",
          "Valet","Varies by Unit","Workshop in Garage"] },
    ]
  },

  // ─── SECTION 12 — Lot Information (PDF pages 10–11) ──────────────────
  {
    id: 12, name: "Lot Information", pdfPages: [10,11],
    fields: [
      { key: "lot_size_area", label: "Lot Size Area", 
        type: "number", required: true },
      { key: "lot_dimensions", label: "Lot Dimensions", 
        type: "text", required: false },
      { key: "lot_size_acreage", label: "Lot Size (Acreage)", 
        type: "select", required: true,
        options: ["< .5 Acre (not Zero)",".5 to < 1 Acre","1 to < 3 Acres",
          "3 to < 5 Acres","5 to < 10 Acres","10 to < 50 Acres",
          "50 to = < 100 Acres","Over 100 Acres","Condo/Townhome Lot",
          "Zero Lot"] },
      { key: "lot_size_unit", label: "Lot Size Unit", 
        type: "radio", required: true,
        options: ["Acres","Square Feet"] },
      { key: "lot_size_source", label: "Lot Size Source", 
        type: "select", required: false,
        options: ["Appraiser","Assessor","Builder","Estimated","Owner",
          "Plans","Public Records","See Remarks","Other"] },
      { key: "easements", label: "Easements", 
        type: "multiselect", required: false,
        options: ["Access","Drainage","Electric","Natural Gas","Pipeline",
          "Telephone","Utilities","Water Lines","Other","None"] },
      { key: "waterfront_yn", label: "Waterfront", 
        type: "yes_no", required: false },
      { key: "waterfront_features", label: "Waterfront Features", 
        type: "multiselect", required: false,
        options: ["Canal (Man Made)","Creek","Dock - Covered",
          "Dock - Enclosed","Dock - Uncovered","Lake Front",
          "Lake Front - Common Area","Lake Front - Corps of Engineers",
          "Lake Front - Main Body","Leasehold","Personal Watercraft Lift",
          "Retaining Wall - Concrete","Retaining Wall - Other",
          "Retaining Wall - Steel","Retaining Wall - Wood","River Front",
          "Water Board Authority-HOA","Water Board Authority-Private",
          "Beach Front"],
        conditionalOn: { key: "waterfront_yn", value: "Yes" } },
      { key: "horse_permitted_yn", label: "Horse Permitted", 
        type: "yes_no", required: false },
      { key: "lot_features", label: "Lot Features", 
        type: "multiselect", required: false,
        options: ["Acreage","Adjacent to Greenbelt","Agricultural",
          "Airstrip","Bayou","Bottom","Brush","Cleared","Corner Lot",
          "Cul-De-Sac","Few Trees","Flag Lot","Greenbelt","Gullies",
          "Hilly","Interior Lot","Irregular Lot","Landscaped","Leasehold",
          "Level","Lrg. Backyard Grass","Many Trees","Cedar","Mesquite",
          "Oak","Pine","Shinnery","Need Fill","No Backyard Grass",
          "On Golf Course","Other","Park View","Pasture",
          "Rock Outcropping","Rolling Slope","Rugged","Sloped",
          "Sprinkler System","Steep Slope","Subdivision","Swamp",
          "Tank/Pond","Taxi-way","Undivided","Varied","Water/Lake View",
          "Waterfront","Zero Lot Line"] },
      { key: "fence_type", label: "Type of Fence", 
        type: "multiselect", required: false,
        options: ["Back Yard","Barbed Wire","Block","Brick","Chain Link",
          "Cross Fenced","Electric","Fenced","Front Yard","Full","Gate",
          "High Fence","Invisible","Masonry","Metal","Net","Partial",
          "Partial Cross","Perimeter","Pipe","Privacy","Rock/Stone",
          "Security","Split Rail","Vinyl","Wire","Wood","Wrought Iron",
          "Other","None"] },
      { key: "lake_pump_yn", label: "Lake Pump", 
        type: "yes_no", required: false },
      { key: "other_structures", label: "Other Structures", 
        type: "multiselect", required: false,
        options: ["Airplane Hangar","Arena","Barn(s)","Boat House",
          "Boiler Operation","Bunk House","Cabana","Cave(s)","Corral(s)",
          "Covered Arena","Garage(s)","Gazebo","Grain Storage","Greenhouse",
          "Guest House","Hunters Cabin","Kennel/Dog Run","Mobile Home",
          "Outbuilding","Outdoor Kitchen","Packing Shed","Pergola",
          "Pool House","Poultry Coop","Private Hangar","Residence",
          "RV/Boat Storage","Second Garage","Second Residence","See Remarks",
          "Separate Entry Quarters","Shed(s)","Silo","Stable(s)","Storage",
          "Tenant House","Tennis Court(s)","Winery","Workshop",
          "Workshop w/Electric","Other","None"] },
      { key: "exterior_features", label: "Exterior Features", 
        type: "multiselect", required: false,
        options: ["Attached Grill","Awning(s)","Balcony","Barbecue",
          "Basketball Court","Boat Slip","Built-in Barbecue","Courtyard",
          "Covered Courtyard","Covered Deck","Covered Patio/Porch","Dock",
          "Dog Run","Electric Grill","Fire Pit","Garden(s)","Gas Grill",
          "Gray Water System","Rain Gutters","Kennel","Lighting",
          "Misting System","Mosquito Mist System","Outdoor Grill",
          "Outdoor Kitchen","Outdoor Living Center","Outdoor Shower",
          "Permeable Paving","Playground","Private Entrance",
          "Private Landing Strip","Private Yard","Rain Barrel/Cistern(s)",
          "RV Hookup","RV/Boat Parking","Sport Court","Stable/Barn",
          "Storage","Storm Cellar","Tennis Court(s)","Uncovered Courtyard",
          "Other"] },
      { key: "soil", label: "Soil", 
        type: "multiselect", required: false,
        options: ["Black","Clay","Fill","Limestone","Rocky/Shale",
          "Sandy Loam","Unknown","Other"] },
      { key: "restrictions", label: "Restrictions", 
        type: "multiselect", required: false,
        options: ["Agricultural","Animals","Architectural","Building",
          "Deed","Development","Easement(s)","Health Department","Hi Line",
          "Inland-Wetland Restr.","Lease While on Market",
          "Mobile Home Only","No Divide","No Known Restriction(s)",
          "No Livestock","No Mobile Home","No Pets","No Restrictions",
          "No Smoking","No Sublease","No Waterbeds","Pet Restrictions",
          "Pipeline","Surface Lease(s)","Timber Lease(s)",
          "Unknown Encumbrance(s)","Other","None"] },
      { key: "vegetation", label: "Vegetation", 
        type: "multiselect", required: false,
        options: ["Brush","Cleared","Crop(s)","Grassed",
          "Heavily Wooded","Partially Wooded","Wooded"] },
      { key: "dock_permitted_yn", label: "Dock Permitted", 
        type: "yes_no", required: false },
      { key: "platted_waterfront_boundary", 
        label: "Platted Waterfront Boundary", 
        type: "text", required: false },
    ]
  },

  // ─── SECTION 13 — Utility Information (PDF page 12) ──────────────────
  {
    id: 13, name: "Utility Information", pdfPages: [12],
    fields: [
      { key: "utilities", label: "Street / Utilities", 
        type: "multiselect", required: true,
        options: ["Aerobic Septic","All Weather Road","Alley","Asphalt",
          "Cable Available","City Sewer","City Water","Co-op Electric",
          "Co-op Membership Included","Co-op Water","Community Mailbox",
          "Concrete","Curbs","Dirt","Electricity Available",
          "Electricity Connected","Electricity Not Available",
          "Gravel/Rock","Individual Gas Meter","Individual Water Meter",
          "Master Gas Meter","Master Water Meter","MUD Sewer","MUD Water",
          "Natural Gas Available","Outside City Limits",
          "Overhead Utilities","Phone Available","Private Road",
          "Private Sewer","Private Water","Propane","Rural Water District",
          "See Remarks","Septic","Sewer Available","Sewer Not Available",
          "Sewer Tap Fee Paid","Sidewalk","Underground Utilities",
          "Unincorporated","Water Tap Fee Paid","Well",
          "No City Services","No Sewer","No Water","Other","None"] },
      { key: "heating", label: "Heating", 
        type: "multiselect", required: false,
        options: ["Active Solar","Central","Electric",
          "ENERGY STAR Equipment","ENERGY STAR Installation",
          "Fireplace Insert","Fireplace(s)","Floor Furnace","Gas Jets",
          "Geothermal","Heat Pump","Humidity Control","Natural Gas",
          "Oil","Passive Solar","Pellet Stove","Propane","Solar",
          "Space Heater","Wall Furnace","Wood Stove","Zoned",
          "Other","None","Radiant Heat Floors"] },
      { key: "cooling", label: "Cooling", 
        type: "multiselect", required: false,
        options: ["Attic Fan","Ceiling Fan(s)","Central Air","Electric",
          "ENERGY STAR Qualified Equipment","Evaporative Cooling",
          "Gas","Geothermal","Heat Pump","Humidity Control","Multi Units",
          "Roof Turbine(s)","Wall Unit(s)","Wall/Window Unit(s)",
          "Window Unit(s)","Zoned","Other","None"] },
      { key: "mud_district_yn", label: "MUD District", 
        type: "yes_no", required: true },
      { key: "special_taxing_authority_yn", label: "Special Taxing Authority", 
        type: "yes_no", required: false },
      { key: "public_improvement_district_yn", 
        label: "Public Improvement District", 
        type: "yes_no", required: false },
    ]
  },

  // ─── SECTION 14 — Environment Info (PDF page 13) ─────────────────────
  {
    id: 14, name: "Environment & Green Features", pdfPages: [13],
    fields: [
      { key: "green_sustainability", label: "Green Sustainability", 
        type: "multiselect", required: false,
        options: ["Conserving Methods","Onsite Recycling Center",
          "Recyclable Materials","Recycled Materials",
          "Regionally-Sourced Materials","Renewable Materials",
          "Salvaged Materials"] },
      { key: "indoor_air_quality", label: "Indoor Air Quality", 
        type: "multiselect", required: false,
        options: ["Integrated Pest Management","Moisture Control",
          "Ventilation"] },
      { key: "building_verification", label: "Building Verification", 
        type: "multiselect", required: false,
        options: ["Certified Passive House","ENERGY STAR Certified Homes",
          "EnerPHit","Green Built N. TX","HERS Index Score",
          "Home Energy Score",
          "Home Energy Upgrade Cert of Energy Efficiency Improvements",
          "Home Energy Upgrade Cert of Energy Efficiency Performance",
          "Home Performance with ENERGY STAR","Indoor airPLUS",
          "LEED For Homes","Living Building Challenge",
          "NGBP - National Green","NGBS New Construction",
          "NGBS Small Projects Remodel","NGBS Whole - Home Remodel",
          "PHIUS+","WaterSense","Zero Energy Ready Home",
          "Pearl Certification"] },
      { key: "green_verification_url", label: "Green Verification URL", 
        type: "text", required: false },
      { key: "green_energy_generation", label: "Green Energy Generation", 
        type: "multiselect", required: false,
        options: ["Hydro Power","Solar","Wind","Assumable","Leased",
          "Owned"] },
      { key: "green_energy_features", label: "Green Energy Features", 
        type: "multiselect", required: false,
        options: ["12 inch+ Attic Insulation","Appliances","Construction",
          "Doors","Drought Tolerant Plants","Energy Recovery Ventilator",
          "Enhanced Air Filtration","ET Irrigation Control",
          "Exposure/Shade","Geo-thermal HVAC","HVAC","Incentives",
          "Insulation","Lighting","Low Flow Commode","Mechanical Fresh Air",
          "Rain / Freeze Sensors","Rain Water Catchment","Roof",
          "Solar Electric System","Solar Electric System - Leased",
          "Solar Electric System - Owned","Solar Hot Water","Thermostat",
          "Waterheater","Windows"] },
      { key: "green_water_features", label: "Green Water Features", 
        type: "multiselect", required: false,
        options: ["Efficient Hot Water Distribution","Gray Water System",
          "Green Infrastructure","Low-Flow Fixtures","Water Recycling",
          "Water-Smart Landscaping"] },
      { key: "green_landscaping", label: "Green Landscaping", 
        type: "multiselect", required: false,
        options: ["Native Landscape","Non-Toxic Fertilizer/Pesticides",
          "Rain Water Harvesting","Veg. (Productive) Garden"] },
      { key: "walk_score", label: "Walk Score", 
        type: "number", required: false },
    ]
  },

  // ─── SECTION 15 — Financial Information (PDF page 14) ────────────────
  {
    id: 15, name: "Financial Information", pdfPages: [14],
    fields: [
      { key: "listing_terms", label: "Listing Terms (Proposed Financing)", 
        type: "multiselect", required: false,
        options: ["1031 Exchange","All Incl Trust Deed","Assumable",
          "Cash","Contact Agent","Contract","Conventional",
          "Convl Assumable","Escalating","Existing Bonds",
          "Federal Land Bank","FHA","FHA Assumable","FHA-203K","Fixed",
          "FMHA","Land Use Fee","Lease Back","Lease Option",
          "Lease Purchase","Lien Release","Not Assumable",
          "Owner Carry 2nd","Owner Will Carry","Priv Financing Avail",
          "Relo Property","Seller Equity Share","Special Funding","Submit",
          "Texas Vet","Trade","Trust Conveyance","Trust Deed",
          "TX VET Assumable","USDA Loan","VA Assumable","VA Loan",
          "VA Reinstmt Reqd","Other"] },
      { key: "concessions", label: "Concessions", 
        type: "yes_no", required: false },
      { key: "possession", label: "Possession", 
        type: "select", required: true,
        options: ["30-60 Days","60-90 Days","Closing/Funding",
          "Lease Outstanding","Negotiable","Specific Date",
          "Subject to Lease","Upon Completion","Other"] },
      { key: "unexempt_taxes", label: "Unexempt Taxes", 
        type: "currency", required: false },
      { key: "loan_type", label: "Loan Type", 
        type: "select", required: true,
        options: ["Assumable Non Qualifying","Assumable Qualifying",
          "Treat As Clear"] },
      { key: "loan_payment_type", label: "Loan Payment Type", 
        type: "select", required: false,
        options: ["Principal & Interest","Principal, Int & Ins.",
          "Principal, Int. & Taxes","Principal, Int. Taxes & Ins.",
          "Other"] },
      { key: "loan_payment", label: "Loan Payment", 
        type: "currency", required: false },
      { key: "loan_balance", label: "Loan Balance", 
        type: "currency", required: false },
      { key: "loan_interest_rate", label: "Loan Interest Rate (%)", 
        type: "number", required: false },
      { key: "orig_mortgage_date", label: "Original Mortgage Date", 
        type: "date", required: false },
      { key: "lender_name", label: "Lender Name", 
        type: "text", required: false },
      { key: "appraiser_name", label: "Appraiser's Name", 
        type: "text", required: false },
      { key: "second_mortgage_yn", label: "Second Mortgage", 
        type: "yes_no", required: true },
      { key: "title_company_preferred", label: "Title Company - Preferred", 
        type: "text", required: false },
      { key: "title_company_phone", label: "Title Company Phone", 
        type: "text", required: false },
      { key: "title_company_location", label: "Title Company Location", 
        type: "text", required: false },
    ]
  },

  // ─── SECTION 16 — HOA Information (PDF page 15) ───────────────────────
  {
    id: 16, name: "HOA Information", pdfPages: [15],
    fields: [
      { key: "hoa_type", label: "HOA Type", 
        type: "select", required: true,
        options: ["Mandatory","Voluntary","None"] },
      { key: "hoa_billing_frequency", label: "HOA Billing Frequency", 
        type: "select", required: false,
        options: ["Annually","Bi-Monthly","Bi-Weekly","Daily","Monthly",
          "One Time","Quarterly","Seasonal","Semi-Annual","Semi-Monthly",
          "Weekly","Other"],
        conditionalOn: { key: "hoa_type", value: ["Mandatory","Voluntary"] } },
      { key: "hoa_dues", label: "HOA Dues", 
        type: "currency", required: false,
        conditionalOn: { key: "hoa_type", value: ["Mandatory","Voluntary"] } },
      { key: "hoa_management_company", label: "HOA Management Company", 
        type: "text", required: false },
      { key: "hoa_management_phone", label: "HOA Management Company Phone", 
        type: "text", required: false },
      { key: "hoa_website", label: "HOA Website", 
        type: "text", required: false },
      { key: "hoa_management_email", label: "HOA Management Email", 
        type: "text", required: false },
      { key: "hoa_includes", label: "HOA Includes", 
        type: "multiselect", required: false,
        options: ["Back Yard Maintenance","Electricity",
          "Front Yard Maintenance","Full Use of Facilities","Gas",
          "Insurance","Internet","Maintenance Grounds",
          "Maintenance Structure","Management Fees","Pest Control",
          "Security","Sewer","Trash","Utilities","Water"] },
    ]
  },

  // ─── SECTION 17 — Agent & Office Info (PDF page 16) ──────────────────
  {
    id: 17, name: "Agent & Office Info", pdfPages: [16],
    fields: [
      // Agent ID auto-populated from logged-in user's mls_id
      { key: "agent_id", label: "Agent ID (MLS)", 
        type: "text", required: true,
        helpText: "Auto-filled from your profile" },
      { key: "list_team_id", label: "List Team ID", 
        type: "text", required: false },
      { key: "co_list_agent_id", label: "Co List Agent ID", 
        type: "text", required: false },
      { key: "supervisor_id", label: "Supervisor ID", 
        type: "text", required: true },
      { key: "list_agent_texting_allowed", label: "List Agent Texting Allowed",
        type: "yes_no", required: false },
      { key: "co_list_agent_texting_allowed", 
        label: "Co List Agent Texting Allowed",
        type: "yes_no", required: false },
      { key: "attribution_listing_override", label: "Listing Override",
        type: "text", required: false },
    ]
  },

  // ─── SECTION 18 — Showing Information (PDF page 17) ──────────────────
  {
    id: 18, name: "Showing Information", pdfPages: [17],
    fields: [
      { key: "special_listing_conditions", label: "Special Listing Conditions",
        type: "select", required: true,
        options: ["Builder","Standard/Individual","Real Estate (Bank) Owned",
          "Bankruptcy Property","HUD Owned","In Foreclosure",
          "Notice Of Default","Probate Listing","Short Sale",
          "Third Party Approval"] },
      { key: "lockbox_type", label: "Lockbox Type", 
        type: "select", required: true,
        options: ["Blue BT LE","Blue iBox","Call Listing Office",
          "Call Seller Direct","Combo","SentriLock","Supra",
          "See Remarks","Other","None"] },
      { key: "key_box_number", label: "Key Box Number", 
        type: "text", required: true },
      { key: "lock_box_location", label: "Lock Box Location", 
        type: "text", required: false },
      { key: "access_gate_code", label: "Access/Gate Code", 
        type: "text", required: false },
      { key: "consent_for_visitors_to_record", 
        label: "Consent for Visitors to Record",
        type: "multiselect", required: false,
        options: ["Audio","Video","None"] },
      { key: "occupant_type", label: "Occupant Type", 
        type: "select", required: false,
        options: ["Owner","Tenant","Vacant"] },
      { key: "occupant_name", label: "Occupant Name", 
        type: "text", required: false },
      { key: "occupant_phone", label: "Occupant Phone", 
        type: "text", required: false },
      { key: "occupant_alternate_phone", label: "Occupant Alternate Phone", 
        type: "text", required: false },
      { key: "notice_surveillance_devices", 
        label: "Notice Surveillance Devices Present",
        type: "multiselect", required: false,
        options: ["Audio","Video","None"] },
      { key: "showing_requirements", label: "Showing Requirements", 
        type: "multiselect", required: true,
        options: ["24 Hour Notice","Appointment Only","Call-Key Box",
          "Combination Lock Box","Courtesy Call (Apps Svc Only)",
          "Day Sleeper","Email Listing Agent","Go (Appt Svc Only)",
          "Go - Key Box","Go Show - No Appt. Needed","Key In Office",
          "Occupied","Pet(s) on Premises","Restricted Hours",
          "Security System","Showing Service","Special","To Be Built",
          "Under Construction","Virtual Showing- Call Agent",
          "See Remarks","No Lock Box","No Sign"] },
      { key: "showing_attended_yn", label: "Showing Attended", 
        type: "yes_no", required: false },
      { key: "owner_name", label: "Owner Name", 
        type: "text", required: true },
      { key: "showing_services", label: "Showing Service(s)", 
        type: "multiselect", required: false,
        options: ["ShowingTime","BrokerBay","None"] },
      { key: "showing_contact_type", label: "Showing Contact Type", 
        type: "select", required: false,
        options: ["Showing Service","Agent","Builder","Occupant","Office",
          "Other","Owner","Property Manager"] },
      { key: "showing_contact_phone", label: "Showing Contact Phone", 
        type: "text", required: false },
      { key: "showing_contact_phone_ext", label: "Showing Contact Phone Ext", 
        type: "text", required: false },
      { key: "showing_instructions", label: "Showing Instructions", 
        type: "textarea", required: false, maxLength: 1000 },
      { key: "showing_instructions_secured", 
        label: "Showing Instructions Secured (Intra Office)",
        type: "textarea", required: false, maxLength: 255 },
    ]
  },

  // ─── SECTION 19 — Remarks (PDF page 18) ──────────────────────────────
  {
    id: 19, name: "Remarks & Description", pdfPages: [18],
    fields: [
      { key: "public_driving_directions", label: "Public Driving Directions", 
        type: "textarea", required: true, maxLength: 300 },
      { key: "property_description", label: "Property Description", 
        type: "textarea", required: false, maxLength: 1000 },
      { key: "excludes", label: "Excludes", 
        type: "textarea", required: false, maxLength: 150 },
      { key: "private_remarks", label: "Private Remarks", 
        type: "textarea", required: false, maxLength: 1000 },
      { key: "intra_office_remarks", label: "Intra Office Remarks", 
        type: "textarea", required: false, maxLength: 225 },
      { key: "listings_appear_on", label: "Listings Will Appear On", 
        type: "multiselect", required: false,
        options: ["Homes.com","Members IDX Websites","NTREIS Translator",
          "Realtor.com","Realtors Property Resource","Syndicate Listing"] },
      { key: "allow_address_display", label: "Allow Address Display", 
        type: "yes_no", required: true },
      { key: "allow_avm", label: "Allow AVM", 
        type: "yes_no", required: true },
      { key: "allow_comments_reviews", label: "Allow Comments/Reviews", 
        type: "yes_no", required: true },
      { key: "allow_internet_display", label: "Allow Internet Display", 
        type: "yes_no", required: true },
    ]
  },

  // ─── SECTION 20 — Condo Information (PDF page 19) ────────────────────
  // Only show this section if property_sub_type = Condominium or Townhouse
  {
    id: 20, name: "Condo Information", pdfPages: [19],
    fields: [
      { key: "complex_name", label: "Complex Name", 
        type: "text", required: false,
        conditionalOn: { key: "property_sub_type", 
          value: ["Condominium","Townhouse"] } },
      { key: "building_number", label: "Building Number", 
        type: "text", required: false },
      { key: "building_stories", label: "Building Stories", 
        type: "number", required: false },
      { key: "floor_location", label: "Floor Location", 
        type: "text", required: false },
      { key: "fha_va_approved_complex", label: "FHA/VA Approved Complex #", 
        type: "text", required: false },
    ]
  },

  // ─── SECTION 21 — Farm & Ranch Info (PDF pages 20–21) ────────────────
  // Only show if property_sub_type = Farm
  {
    id: 21, name: "Farm & Ranch Info", pdfPages: [20,21],
    fields: [
      { key: "farm_residences", label: "# Residences", 
        type: "number", required: false },
      { key: "farm_stock_tanks", label: "# Stock Tanks/Ponds", 
        type: "number", required: false },
      { key: "farm_barns", label: "# Barns", 
        type: "number", required: false },
      { key: "farm_lakes", label: "# Lakes", 
        type: "number", required: false },
      { key: "farm_wells", label: "# Wells", 
        type: "number", required: false },
      { key: "farm_water_meters", label: "# Separate Water Meters", 
        type: "number", required: false },
      { key: "present_use", label: "Present Use", 
        type: "multiselect", required: false,
        options: ["Agricultural","Cattle","Commercial","Crops",
          "Crops and Livestock","Dairy","Development","Exotics",
          "Farm Sink","Feed Lot","Fishery","Grazing",
          "Highway/Tourist Service","Horses","Hunting/Fishing",
          "Industrial","Investment","Livestock","Manufactured Home",
          "Mini-Storage","Mobile Home","Multi-Family",
          "Orchards/Vineyards","Pasture","Place of Worship","Poultry",
          "Ranch","Recreational","Residential","Resort","Retail",
          "Sheep/Goats","Single Family","Subdevelopment","Swine",
          "Timber","Truck Farm","Unimproved","Vacant","Warehouse",
          "See Remarks","Other"] },
      { key: "bottom_land_acres", label: "Bottom Land Acres", 
        type: "number", required: false },
      { key: "cultivated_acres", label: "Cultivated Acres", 
        type: "number", required: false },
      { key: "irrigated_acres", label: "Irrigated Acres", 
        type: "number", required: false },
      { key: "pasture_acres", label: "Pasture Acres", 
        type: "number", required: false },
      { key: "topography", label: "Topography", 
        type: "textarea", required: false, maxLength: 75 },
      { key: "proposed_use", label: "Proposed Use", 
        type: "multiselect", required: false,
        options: ["Agricultural","Barndominium","Cattle","Commercial",
          "Dairy","Development","Equine","Exotics","Farm Sink",
          "Feed Lot","Fishery","Grazing","Highway/Tourist Service",
          "Horses","Hunting/Fishing","Industrial","Investment",
          "Livestock","Manufactured Home","Mini-Storage","Mixed Use",
          "Mobile Home","Multi-Family","Orchards/Vineyards","Pasture",
          "Place of Worship","Poultry","Ranch","Recreational",
          "Residential","Resort","Retail","Sheep/Goats","Single Family",
          "Subdevelopment","Swine","Timber","Truck Farm","Unimproved",
          "Vacant","Warehouse","See Remarks","Other"] },
      { key: "crop_retire_program_yn", label: "Crop Retire Program", 
        type: "yes_no", required: false },
      { key: "land_leased_yn", label: "Land Leased", 
        type: "yes_no", required: false },
      { key: "agri_exemption_yn", label: "Agricultural Exemption", 
        type: "yes_no", required: false },
      { key: "aerial_photo_available_yn", label: "Aerial Photo Available", 
        type: "yes_no", required: false },
      { key: "crop_grasses", label: "Crop/Grasses", 
        type: "multiselect", required: false,
        options: ["Bluestem","Buffalo Grass","Coastal Bermuda",
          "Common Bermuda","Emmedo Love Grass","Hardwood Timber",
          "Improved Pasture","Irrigated","Klein Grass","Main Grass",
          "Native","Non Irrigated","Orchard","Produce","Renner Love Grass",
          "Row Crop","Small Grain","Softwood Timber","Vineyard","Other"] },
      { key: "road_surface_type", label: "Road Surface Type", 
        type: "multiselect", required: false,
        options: ["Asphalt","Concrete","Dirt","Gravel","Oil & Screen"] },
      { key: "road_frontage_desc", label: "Road Frontage Description", 
        type: "multiselect", required: false,
        options: ["City Street","County Road","Curbs/Gutters","Easement",
          "FM Road","Highway","Interstate","Private Road","Sidewalk",
          "State Road","Storm Sewer","Other","None"] },
      { key: "surface_rights", label: "Surface Rights", 
        type: "multiselect", required: false,
        options: ["All","Easement","Exist","Mineral Easement","Other"] },
      { key: "horse_barn_info", label: "Horse/Barn Info", 
        type: "multiselect", required: false,
        options: ["Arena","Barn(s)","Breeding Barn","Electric to Barn",
          "Equestrian Center","Equipment Barn","Farrowing Barn",
          "Feeder Pig Barn","Goat/Sheep Barn","Hay Barn","Hay Loft",
          "Holding Pens","Indoor Arena","Living Quarters","Loaf Shed(s)",
          "Mare Motel","Parlor Dairy Barn","Round Pens","Show Barn",
          "Stable(s)","Stanchion Dairy Barn","Tack Room",
          "Temperature Controlled","Wash Rack","Water to Barn","Other"] },
      { key: "ranch_name", label: "Ranch Name", 
        type: "text", required: false },
      { key: "farm_ranch_misc", label: "Farm/Ranch Miscellaneous", 
        type: "multiselect", required: false,
        options: ["Auto Feed Mill","Calf Tables","Cattle Guard",
          "Cattle Working Pen","Cold Storage Facility","Corrals",
          "Fenced for Cattle","Fenced for Exotic Birds/Game",
          "Fenced for Horses","Helipad","Hot Walker","Kennels",
          "Loading Chute","Outdoor Arena","Perm. Squeeze Chutes",
          "Walker","Windmill","Other"] },
      { key: "barn_type", label: "Barn Type", 
        type: "multiselect", required: false,
        options: ["Barn(s)","Breeding","Equipment","Farrowing",
          "Feeder Pig","Goat/Sheep","Hay Barn","Mare Motel",
          "Parlor Dairy","Show Barn","Stable(s)","Stanchion Dairy"] },
      { key: "stalls_in_barn", label: "# Stalls in Barn", 
        type: "number", required: false },
      { key: "barn_length", label: "Barn Length (ft)", 
        type: "number", required: false },
      { key: "barn_width", label: "Barn Width (ft)", 
        type: "number", required: false },
      { key: "feet_to_road", label: "Feet to the Road/Road Fntg Distance", 
        type: "number", required: false },
    ]
  },

  // ─── SECTION 22 — Review & Submit (no PDF page — LP Hub only) ────────
  {
    id: 22, name: "Review & Submit", pdfPages: [],
    fields: [
    ],
  },

]

export function isFieldVisible(field: NtreisField, formData: FormData): boolean {
  if (!field.conditionalOn) return true
  const { key, value } = field.conditionalOn
  const current = formData[key]
  if (Array.isArray(value)) {
    return typeof current === 'string' && value.includes(current)
  }
  return current === value
}

export function isSectionVisible(section: NtreisSection, formData: FormData): boolean {
  if (section.id === 20) {
    const subType = formData.property_sub_type
    return subType === 'Condominium' || subType === 'Townhouse'
  }
  if (section.id === 21) {
    return formData.property_sub_type === 'Farm'
  }
  return true
}

export function isFieldFilled(value: unknown): boolean {
  if (value === undefined || value === null) return false
  if (typeof value === 'string') return value.trim().length > 0
  if (typeof value === 'number') return !Number.isNaN(value)
  if (typeof value === 'boolean') return true
  if (Array.isArray(value)) return value.length > 0
  if (typeof value === 'object') {
    const row = value as RoomRowValue
    const hasLevel = typeof row.level === 'string' && row.level.trim().length > 0
    const hasLength =
      row.length !== undefined &&
      row.length !== null &&
      String(row.length).trim().length > 0
    const hasWidth =
      row.width !== undefined &&
      row.width !== null &&
      String(row.width).trim().length > 0
    const hasFeatures = Array.isArray(row.features) && row.features.length > 0
    return hasLevel || hasLength || hasWidth || hasFeatures
  }
  return false
}

export function getSectionStatus(section: NtreisSection, formData: FormData): SectionStatus {
  const visibleFields = section.fields.filter((field) => isFieldVisible(field, formData))
  const requiredFields = visibleFields.filter((field) => field.required)

  if (requiredFields.length === 0) {
    const anyFilled = visibleFields.some((field) => isFieldFilled(formData[field.key]))
    return anyFilled ? 'complete' : 'empty'
  }

  const filledRequired = requiredFields.filter((field) => isFieldFilled(formData[field.key]))
  if (filledRequired.length === 0) return 'empty'
  if (filledRequired.length === requiredFields.length) return 'complete'
  return 'partial'
}

export function getVisibleSections(formData: FormData): NtreisSection[] {
  return NTREIS_SECTIONS.filter((section) => isSectionVisible(section, formData))
}

export function countRequiredRemaining(sections: NtreisSection[], formData: FormData): number {
  let count = 0
  for (const section of sections) {
    if (!isSectionVisible(section, formData)) continue
    for (const field of section.fields) {
      if (!field.required) continue
      if (!isFieldVisible(field, formData)) continue
      if (!isFieldFilled(formData[field.key])) count += 1
    }
  }
  return count
}
